<div id="footer">
	&copy; 2009 Bitmap University | 
	<a href="http://www.bitmapu.com">Home</a> | 
	<a href="http://www.bitmapu.com/pages/lbl.php">Video</a> |
	<a href="http://www.bitmapu.com/pages/login.php">Login</a></div>
</div>
</body>

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-10469485-1");
pageTracker._trackPageview();
} catch(err) {}</script>

</html>