<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Bitmap University | <?php echo $pageTitle ?></title>
<link rel="stylesheet" type="text/css" href="http://www.bitmapu.com/assets/styles/siteStyles.css" />
<link rel="shortcut icon" href="http://www.bitmapu.com/assets/images/shortcut.ico" />
<!--[if lte IE 7]>
<style type="text/css">
.menu_wrapper {
  margin-top:5px;
  }
</style>
<![endif]-->
</head>
<body>

<div id="wrapper-main">
	<div id="banner">
		<h1><a href="/">Bitmap University</a></h1>
	</div>	 
	
	<div id="menu">
		<a href="/">Home</a>
		<a href="http://www.bitmapu.com/pages/lbl.php">Video</a>
	</div>